version: "3.8"

services:
  app:
    build: .
    command: gunicorn schoolmanagement.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/staticfiles
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:12.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - db.env
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/www/staticfiles
    ports:
      - 80:80
    depends_on:
      - app
volumes:
  postgres_data:
  static_volume:
